name: StoryBook Deploy S3[pull_request]

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_URL: ${{ secrets.S3_URL }}
      API_ENDPOINT: ${{ github.event.issue.pull_request.url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.issue.number }}
    steps:
    - id: check
        # If the comment contains the string deploy-storybook and pull_requrest, then run
      if: "contains(github.event.comment.body, 'deploy-storybook') && github.event.issue.pull_request" 
      run: |
        branch=`curl -X GET -H "Authorization: token ${GITHUB_TOKEN}" ${API_ENDPOINT} | jq -r '.head.ref'`
        echo ::set-output name=branch::$branch
     
    - name: Checkout
      if: "steps.check.outputs.branch" 
      uses: actions/checkout@v2

    - name: Setup node
      if: "steps.check.outputs.branch"
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Configure AWS credentials
      if: "steps.check.outputs.branch" 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Build StoryBook
      if: "steps.check.outputs.branch" 
      run: |
        yarn install
        yarn build-storybook
      
    - name: Upload file to S3
      if: "steps.check.outputs.branch" 
      run: |
        aws s3 sync ./storybook-static s3://$S3_BUCKET_NAME/pr-$GITHUB_PULL_REQUEST_NUMBER --quiet
        
    - name: Create URL
      if: "steps.check.outputs.branch" 
      run: |
        curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -i ${API_ENDPOINT} -d "`printf '{\"body\":\"deploy to %s\"}' ${S3_URL}/"pr-"${GITHUB_PULL_REQUEST_NUMBER}`"
        
# Slack notification
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            username: 'StoryBookURL通知BOT',
            icon_emoji: ':github:',
            attachments: [{
              "color": '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "text": "StoryBookのURLを生成しました。確認をお願いします。",
              "fields": [
                {
                  "title": "変更内容",
                  "value": "${{ github.event.issue.title }}"
                },
                {
                  "title": "URL",
                  "value": "${{ secrets.S3_URL }}/pr-${{ github.event.issue.number }}"
                }],
              }
            ]
          }
